"""Tests for consistency between text file report and YAML service response.

Both outputs are generated by a single watchman.report service call but travel
through separate code paths inside async_handle_report (services.py):

  Text/file report  → coordinator._missing_*_cache   (computed at T1, inside async_force_parse)
  YAML response     → async_get_detailed_report_data  (computed at T2, after the file is written)

Test data (tests/data/reports/test_report_consistency/) covers five parent-context variants
so that any future regression that breaks one of the paths for a specific source type
is caught immediately:

  Source                   Entity                          Parent type
  ──────────────────────── ─────────────────────────────── ────────────────
  automations.yaml         sensor.missing_from_automation  automation
  scripts.yaml             sensor.missing_from_script      script
  .storage/lovelace        sensor.missing_from_lovelace    (none)
  .storage/core.config…    sensor.miss_helper_group        helper_group
  .storage/core.config…    sensor.miss_helper_tmpl         helper_template
  config.yaml              sensor.missing_parentless       (none)

  scripts.yaml             script.missing_script_action    (missing action, script parent)

Divergence risk notes
─────────────────────
  HIGH   automation / script parents → non-empty data["automations"] → _is_safe_to_report
         runs filter-context-dependent logic (exclude_disabled, automation_map).
         A FilterContext rebuild between T1 and T2 can change which items pass.

  MEDIUM helper_group / helper_template → automations = {}, so _is_safe_to_report skips
         parent checks, but context is stored in occurrences["context"].  If hub.py or the
         coordinator's flatten/format helpers diverge in how they pass context, one report
         may lose the structured metadata while the other keeps it.

  LOW    Lovelace / parentless → no context, no parent checks.  Count parity (Test 1)
         is sufficient; no additional context assertions are added.
"""

import re
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from custom_components.watchman.const import (
    CONF_INCLUDED_FOLDERS,
    CONF_REPORT_PATH,
    CONF_SECTION_APPEARANCE_LOCATION,
    DOMAIN,
)

from tests import async_init_integration


# ---------------------------------------------------------------------------
# Shared setup helper
# ---------------------------------------------------------------------------

async def _setup_and_call_report(hass, tmp_path, new_test_data_dir):
    """Initialise integration for test_report_consistency data, call watchman.report.

    Returns (config_entry, response, text_content).
    The caller is responsible for tearing down the config entry.
    """
    config_dir = str(Path(new_test_data_dir) / "reports" / "test_report_consistency")
    hass.config.config_dir = config_dir
    hass.config.path = MagicMock(side_effect=lambda *args: str(tmp_path.joinpath(*args)))

    report_file = tmp_path / "watchman_report.txt"

    config_entry = await async_init_integration(
        hass,
        add_params={
            CONF_INCLUDED_FOLDERS: config_dir,
            CONF_SECTION_APPEARANCE_LOCATION: {
                CONF_REPORT_PATH: str(report_file),
            },
        },
    )

    response = await hass.services.async_call(
        DOMAIN,
        "report",
        {"create_file": True},
        blocking=True,
        return_response=True,
    )
    await hass.async_block_till_done()

    assert report_file.exists(), "Text report file was not created by the service"
    text_content = report_file.read_text(encoding="utf-8")

    return config_entry, response, text_content


def _parse_text_counts(content: str) -> tuple[int, int]:
    """Return (entity_count, action_count) from text report summary lines."""
    entity_match = re.search(r"-== Missing (\d+) entity\(ies\)", content)
    action_match = re.search(r"-== Missing (\d+) action\(s\)", content)
    return (
        int(entity_match.group(1)) if entity_match else 0,
        int(action_match.group(1)) if action_match else 0,
    )


# ---------------------------------------------------------------------------
# Test 1 – count parity
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_text_yaml_missing_counts_match(hass, new_test_data_dir, tmp_path):
    """Unique-entity and unique-action counts must be identical in both report formats.

    The text report header ("Missing N entity(ies) from …") and the number of distinct
    ``id`` values in the YAML response list must always agree.  A divergence here means
    the two code paths inside async_handle_report produced structurally different results,
    regardless of the specific entity type that caused it.
    """
    config_entry, response, text_content = await _setup_and_call_report(
        hass, tmp_path, new_test_data_dir
    )
    try:
        yaml_entity_count = len({e["id"] for e in response["missing_entities"]})
        yaml_action_count = len({a["id"] for a in response["missing_actions"]})

        text_entity_count, text_action_count = _parse_text_counts(text_content)

        assert yaml_entity_count == text_entity_count, (
            f"Entity count divergence: text report shows {text_entity_count}, "
            f"YAML response contains {yaml_entity_count} unique IDs.  "
            "The two code paths inside async_handle_report produced different results."
        )
        assert yaml_action_count == text_action_count, (
            f"Action count divergence: text report shows {text_action_count}, "
            f"YAML response contains {yaml_action_count} unique IDs.  "
            "The two code paths inside async_handle_report produced different results."
        )
    finally:
        await hass.config_entries.async_unload(config_entry.entry_id)
        await hass.async_block_till_done()


# ---------------------------------------------------------------------------
# Test 3 – per-source-type presence and context preservation
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_all_source_types_present_in_both_reports(hass, new_test_data_dir, tmp_path):
    """Entities and actions from every source type appear in both text and YAML reports.

    Beyond simple presence, this test asserts that structured context is preserved end-to-end
    in the YAML response for the source types where context loss is most likely to occur
    due to future refactoring:

      • automation-parented  (HIGH risk – same _is_safe_to_report path as scripts)
      • script-parented      (HIGH risk)
      • helper_group         (MEDIUM risk – context stored in occurrences["context"])
      • helper_template      (MEDIUM risk)

    Lovelace and parentless entities have no structured context, so their presence in
    both reports (covered by Test 1's count check) is the only meaningful invariant.
    """
    config_entry, response, text_content = await _setup_and_call_report(
        hass, tmp_path, new_test_data_dir
    )
    try:
        yaml_entity_ids = {e["id"] for e in response["missing_entities"]}
        yaml_action_ids = {a["id"] for a in response["missing_actions"]}

        # ── HIGH RISK: automation-parented ──────────────────────────────────
        # Entities inside automation definitions go through _is_safe_to_report with
        # a non-empty automations set.  If FilterContext is rebuilt between T1 and T2
        # (e.g. automation toggled), exclude_disabled logic may filter differently.

        assert "sensor.missing_from_automation" in yaml_entity_ids, (
            "Entity inside an automation definition is absent from the YAML response."
        )
        assert "sensor.missing_from_automation" in text_content, (
            "Entity inside an automation definition is absent from the text report."
        )
        automation_ctx_occurrences = [
            e for e in response["missing_entities"]
            if e["id"] == "sensor.missing_from_automation"
            and (e.get("context") or {}).get("parent_type") == "automation"
        ]
        assert automation_ctx_occurrences, (
            "YAML response must include at least one occurrence of "
            "sensor.missing_from_automation with parent_type='automation' context.  "
            "Context loss here indicates a regression in hub._get_all_items_sync or "
            "coordinator.async_get_detailed_report_data."
        )

        # ── HIGH RISK: script-parented (entity) ─────────────────────────────
        assert "sensor.missing_from_script" in yaml_entity_ids, (
            "Entity inside a script definition is absent from the YAML response."
        )
        assert "sensor.missing_from_script" in text_content, (
            "Entity inside a script definition is absent from the text report."
        )
        script_entity_ctx_occurrences = [
            e for e in response["missing_entities"]
            if e["id"] == "sensor.missing_from_script"
            and (e.get("context") or {}).get("parent_type") == "script"
        ]
        assert script_entity_ctx_occurrences, (
            "YAML response must include at least one occurrence of "
            "sensor.missing_from_script with parent_type='script' context."
        )

        # ── HIGH RISK: script-parented (action) ─────────────────────────────
        assert "script.missing_script_action" in yaml_action_ids, (
            "Action called inside a script definition is absent from the YAML response."
        )
        assert "script.missing_script_action" in text_content, (
            "Action called inside a script definition is absent from the text report."
        )

        # ── MEDIUM RISK: helper_group ────────────────────────────────────────
        # helper_group entities have automations={}, so _is_safe_to_report skips the
        # parent filter.  However, context is carried through occurrences["context"].
        # If hub.py stops emitting helper context, or if async_get_detailed_report_data
        # starts re-fetching differently, the YAML may silently lose the structured
        # metadata while the text report (cached at T1) still exposes it via
        # format_occurrences.

        assert "sensor.miss_helper_group" in yaml_entity_ids, (
            "Entity inside a helper group is absent from the YAML response."
        )
        assert "sensor.miss_helper_group" in text_content, (
            "Entity inside a helper group is absent from the text report."
        )
        group_ctx_occurrences = [
            e for e in response["missing_entities"]
            if e["id"] == "sensor.miss_helper_group"
            and (e.get("context") or {}).get("parent_type") == "helper_group"
        ]
        assert group_ctx_occurrences, (
            "YAML response must include at least one occurrence of "
            "sensor.miss_helper_group with parent_type='helper_group' context.  "
            "Context loss here indicates a regression in the core.config_entries parser "
            "or in how hub._get_all_items_sync propagates helper context."
        )

        # ── MEDIUM RISK: helper_template ─────────────────────────────────────
        assert "sensor.miss_helper_tmpl" in yaml_entity_ids, (
            "Entity inside a helper template is absent from the YAML response."
        )
        assert "sensor.miss_helper_tmpl" in text_content, (
            "Entity inside a helper template is absent from the text report."
        )
        template_ctx_occurrences = [
            e for e in response["missing_entities"]
            if e["id"] == "sensor.miss_helper_tmpl"
            and (e.get("context") or {}).get("parent_type") == "helper_template"
        ]
        assert template_ctx_occurrences, (
            "YAML response must include at least one occurrence of "
            "sensor.miss_helper_tmpl with parent_type='helper_template' context."
        )

        # ── LOW RISK: Lovelace ───────────────────────────────────────────────
        # No structured context; count parity (Test 1) is the primary guard.
        # Presence check here ensures the Lovelace parser is not accidentally
        # broken by changes to the storage file scanning logic.
        assert "sensor.missing_from_lovelace" in yaml_entity_ids, (
            "Entity inside a Lovelace dashboard is absent from the YAML response."
        )
        assert "sensor.missing_from_lovelace" in text_content, (
            "Entity inside a Lovelace dashboard is absent from the text report."
        )

        # ── LOW RISK: parentless ─────────────────────────────────────────────
        # Simplest case; count parity is the primary guard.
        assert "sensor.missing_parentless" in yaml_entity_ids, (
            "Parentless entity (referenced in a plain config file) is absent from the YAML response."
        )
        assert "sensor.missing_parentless" in text_content, (
            "Parentless entity (referenced in a plain config file) is absent from the text report."
        )

    finally:
        await hass.config_entries.async_unload(config_entry.entry_id)
        await hass.async_block_till_done()
