#sensor.test1_unknown
#sensor.test2_missing
#sensor.test3_unavail
#sensor.test4_avail
# 检查非UTF8编码的支持

- alias: "Test Auto: Unknown Sensor"
  id: test_auto_unknown
  trigger:
    - platform: state
      entity_id: sensor.test1_unknown
  action:
    - delay: "00:00:00"

- alias: "Test Auto: Missing Sensor"
  id: test_auto_missing
  trigger:
    - platform: state
      entity_id: sensor.test2_missing
  action:
    - delay: "00:00:00"

- alias: "Test Auto: Unavailable Sensor"
  id: test_auto_unavail
  trigger:
    - platform: state
      entity_id: sensor.test3_unavail
  action:
    - delay: "00:00:00"

- alias: "Test Auto: Available Sensor"
  id: test_auto_avail
  trigger:
    - platform: state
      entity_id: sensor.test4_avail
  action:
    - delay: "00:00:00"
