- id: "explicit_id_case"
  alias: "Any Alias Here"
  trigger:
      - platform: state
        entity_id: sensor.missing_case_id_only
  action: []

- alias: "Only Alias Latin"
  trigger:
      - platform: state
        entity_id: sensor.missing_case_alias_latin
  action: []

- alias: "Тестовая Автоматизация"
  trigger:
      - platform: state
        entity_id: sensor.missing_case_alias_cyrillic
  action: []

- id: "priority_id"
  alias: "Ignored Alias Slug"
  trigger:
      - platform: state
        entity_id: sensor.missing_case_priority
  action: []

- alias: "Complex: Alias (With) [Brackets] & Symbols!"
  trigger:
      - platform: state
        entity_id: sensor.missing_case_complex
  action: []
