#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

scripts/install/pip_packages "pip>=24.2"
scripts/install/pip_packages setuptools wheel
scripts/install/pip_packages \
    --requirement requirements.txt \
    --requirement requirements_test.txt

#pre-commit  install --config .github/pre-commit-config.yaml
