name: "Upload release"

on:
  release:
    types: 
      - published

permissions: {}

jobs:
  release:
    name: "Upload release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/watchman"
          zip watchman.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: "softprops/action-gh-release@v2.0.9"
        with:
          files: ${{ github.workspace }}/custom_components/watchman/watchman.zip
